### ISSUE TITLE
Ubuntu 22.04 crash

### ISSUE THREAD

**Issue by Louis-Simon22** [midoshouse/ootr-multiworld#29]
Hello. 

Thanks for supporting linux. I'm on ubuntu 22.04
I was trying to get it working and used the installer. The emulator crashes after a few seconds with the following logs

[EmuHawkMono_laststderr.txt](https://github.com/midoshouse/ootr-multiworld/files/12064321/EmuHawkMono_laststderr.txt)
[EmuHawkMono_laststdout.txt](https://github.com/midoshouse/ootr-multiworld/files/12064322/EmuHawkMono_laststdout.txt)

I also tried the manual install. And bizhawk works until I add the dlls in the ExternalTools folder.

**Comment by fenhl** [comment]
Thank you for reporting. Can you check if installing the [`libcanberra-gtk-module`](https://packages.ubuntu.com/jammy/libcanberra-gtk-module) package fixes the crash or at least changes the log output? If that's the case, I'd just have to make sure this is handled by the installer.

**Comment by Louis-Simon22** [comment]
Hi,

No change even with the library installed.

**Comment by fenhl** [comment]
I'll see if I can reproduce the issue on a fresh Ubuntu install. If you have any other ideas, let me know.

**Comment by fenhl** [comment]
After reproducing the crash, I had another look at the stack trace and realized that this was an issue I'd run into during initial testing, caused by BizHawk attempting to display an `.ico` image with a 256x256 PNG layer. I thought I had already fixed this by removing that layer from the copy of the icon used by BizHawk, but I guess that change got accidentally reverted at some point, because the layer does exist in the current version of the file.
